---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: telegram-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    receiver: telegram-receiver
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    matchers:
      - name: severity
        value: "critical|warning"
        matcherType: regex
  receivers:
    - name: telegram-receiver
      telegramConfigs:
        - chatID:
            key: chat-id
            name: alertmanager-telegram
          apiKey:
            key: telegram-bot-token
            name: alertmanager-telegram
          sendResolved: true
