---
apiVersion: v1
kind: Namespace
metadata:
  name: hermes-agent
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: hermes-agent-chart
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/javiee/hermes-agent-helm-chart
  ref:
    branch: main
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: hermes-agent
  namespace: flux-system
spec:
  interval: 30m
  chart: ./
  sourceRef:
    kind: GitRepository
    name: hermes-agent-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hermes-agent
  namespace: hermes-agent
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: hermes-agent
    namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      size: 10Gi
      mountPath: /data

    nodeSelector:
      kubernetes.io/hostname: lh-satellite

    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
