apiVersion: k8s.ngrok.com/v1alpha1
kind: Tunnel
metadata:
  name: llama-swap
  namespace: ngrok-operator
  labels:
    app: llama-swap
spec:
  credentialsRef: ngrok-credentials
  publicAddress:
    type: tcp
  target:
    sessionEmbedding: false
    config:
      addr: 192.168.10.122:9090
      proto: tcp
