{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes-agent.fullname" . }}-config
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if .Values.config.values }}
    {{- .Values.config.values | nindent 4 }}
    {{- end }}
  {{- if .Values.config.soul }}
  SOUL.md: |
    {{- .Values.config.soul | nindent 4 }}
  {{- end }}
{{- end }}
